name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            williecadete/lxdexplorer-web
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            williecadete/lxdexplorer-web:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Checkout Infra code
        uses: actions/checkout@v4
        with:
          repository: willie-cadete/homelab
          token: ${{ secrets.GH_PAT }}
          path: infra

      - name: Update Docker Image
        run: |
          echo "image: williecadete/lxdexplorer-web:${{ steps.meta.outputs.tags }}"
          sed -i "s|image: williecadete\/lxdexplorer-web:.*|image: williecadete\/lxdexplorer-web:${{ steps.meta.outputs.tags }}|" kubernetes/manifests/lxdexplorer-web/deployment.yml
          git commit -m "Update lxdexplorer-web image to ${{ steps.meta.outputs.tags }}"
          git push
